### ISSUE TITLE
Exception: Object reference not set to an instance of an object - when creating a world

### ISSUE THREAD

**Issue by WickedSchnitzel** [ApacheTech-VintageStory-Mods/MinimalMapping#6] opened 2024-09-14 08:07 UTC
14.9.2024 10:04:18 [Error] Exception: Object reference not set to an instance of an object.
   at ApacheTech.VintageMods.MinimalMapping.Features.MinimalWorldMap.Patches.MinimalWorldMapClientPatches.Harmony_WorldMapManager_OnLvlFinalize_Postfix(ICoreClientAPI ___capi)
   at Vintagestory.GameContent.WorldMapManager.OnLvlFinalize_Patch1(WorldMapManager this)
   at Vintagestory.Server.ServerEventAPI.OnServerStage(EnumServerRunPhase runPhase) in VintagestoryLib\Server\API\ServerEventAPI.cs:line 141
   at Vintagestory.Server.ServerSystemModHandler.OnBeginRunGame() in VintagestoryLib\Server\Systems\ModHandler.cs:line 82
   at Vintagestory.Server.ServerMain.EnterRunPhase(EnumServerRunPhase runPhase) in VintagestoryLib\Server\ServerMain.cs:line 624
   at Vintagestory.Server.ServerMain.Launch() in VintagestoryLib\Server\ServerMain.cs:line 558
   at Vintagestory.Client.ClientProgram.ServerThreadStart() in VintagestoryLib\Client\ClientProgram.cs:line 390

**Comment by ApacheTech** [comment] 2024-09-15 18:23
Could you please include your log files.

Log into the game, allow it to crash. Then zip your entire Logs folder, and upload it here.

**Comment by ApacheTech** [comment] 2024-09-24 02:26
Duplicate of #9. Now fixed in 2.2.2.

**Closed as completed by ApacheTech** 2024-09-24 02:26 UTC
